# Environment Args
output_root: '/home/francois/Projects/data/sessions'
pytorch_data_dir: '/home/francois/Projects/data/training'
submitting_to_aml: false

# Dataset args
dataset: "cube_checker"

# Model Args
model_type: "deepraynet0301-1248_2"
activation_type: "token" # no effect for resnets

# Upsampling args
outlier_detection: True # Wether to use an uncertainty weighed MSE loss
upsampler_type: "jbu_stack"
downsampler_type: "attention"
max_pad: 20
max_zoom: 2
n_jitters: 5
random_projection: 30
crf_weight: 0.001
filter_ent_weight: 0.0
tv_weight: 0.0

implicit_sup_weight: 1.0

# Training args
batch_size: 4
epochs: 1
num_gpus: 1
num_workers: 24
lr: 1e-3

# No need to change
hydra:
  run:
    dir: "."
  output_subdir: ~

